testdlm: testdlm.cpp
	g++ -O3 -std=c++11 -I/opt/local/Library/Frameworks/R.framework/Headers/ -L/opt/local/Library/Frameworks/R.framework/Libraries/ -I../../../src/ ../../../src/rng/BasicRNG.cc ../../../src/util/logger.cc ../../../src/dist/brmath/build/libbrmath.a ./testdlm.cpp -o testdlm -lR
